# WhatATheme
markdown: kramdown

# URL of the Site
url: https://pochsarah.github.io
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Sarah Poch
# Description of the Site
description: An e-portofolio 
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: https://cdn.pixabay.com/photo/2016/01/19/17/29/earth-1149733_960_720.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: /
facebook_username: /
#twitter_username: /
#instagram_username: / 
linkedin_username: sarah-poch
github_username: pochsarah

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
#disqus-shortname: thedevslot

# Name of the Author
author-name: Sarah Poch
# URL for the Image of the Author
author-image: ./assets/images/profil.jpeg
# 60 Words About the Author
author-about: Welcome to my e-portofolio ! My name is Sarah Poch and I am a student from EMJMD – Copernicus in Digital Earth. After my Bsc in Computer Science, I have decided to join this double master degree and study GeoData Science. This track is hosted by the University of Salzburg (Austria) and the University of South Brittany (France). 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/pochsarah

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
